# ==== CONFIGURE =====
# Use a Node 16 base image
FROM  node:18-bullseye 
# Set the working directory to /app inside the container
WORKDIR /app
# Copy app files
COPY . .
#=== BUILD ====
RUN npm install -g npm@9.7.1
RUN npm install  --legacy-peer-deps
# Build the app
RUN npm run build
# ==== RUN =======
# Set the env to "production"
ENV NODE_ENV production
# Expose the port on which the app will be running (3000 is the default that `serve` uses)
EXPOSE 3000
# Start the app
CMD [ "npx", "serve", "build" ]
