/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/modelsmodels/scene2.gltf 
*/

import React, { useRef, useEffect } from "react";
import * as THREE from "three";
import { motion } from "framer-motion-3d";
import { useGLTF, useTexture, useVideoTexture } from "@react-three/drei";
import { animate, useMotionValue } from "framer-motion";
import { useFrame } from "@react-three/fiber";

export function Office2(props) {
  const { section } = props;

  const { nodes, materials } = useGLTF(
    "models/portfolio_scene_baked_final.gltf"
  );
  const texture = useTexture("textures/baked.jpg");
  const textureVSCode = useVideoTexture("textures/vscode.mp4");

  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 1,
  });

  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.2,
  });

  const textureOpacity = useMotionValue(0);
  const glassTextureOpacity = useMotionValue(0);

  useEffect(() => {
    animate(textureOpacity, section === 0 ? 1 : 0);
    animate(glassTextureOpacity, section === 0 ? 0.42 : 0);
  }, [section]);

  useFrame(() => {
    textureMaterial.opacity = textureOpacity.get();
    textureGlassMaterial.opacity = glassTextureOpacity.get();
  });
  return (
    <group {...props} dispose={null}>
      <group
        name="Desk"
        position={[-0.074, 0, -1.521]}
        rotation={[0, -Math.PI / 2, 0]}
      >
        <mesh
          name="Plane001_Plane002_BlackWood001"
          geometry={nodes.Plane001_Plane002_BlackWood001.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Plane001_Plane002_BlackWood001_1"
          geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Plane001_Plane002_BlackWood001_2"
          geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Plane001_Plane002_BlackWood001_3"
          geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Plane001_Plane002_BlackWood001_4"
          geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry}
          material={textureMaterial}
        />
      </group>
      <group name="SM_ShelfSM_Shelf1" position={[-0.011, 1.694, -2.038]}>
        <mesh
          name="SM_ShelfSM_Shelf1_1"
          geometry={nodes.SM_ShelfSM_Shelf1_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="SM_ShelfSM_Shelf1_1_1"
          geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry}
          material={textureMaterial}
        />
      </group>
      <motion.group
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
        name="LavaLamp"
        position={[-0.57, 2.071, -1.986]}
      >
        <mesh
          name="Node-Mesh001"
          geometry={nodes["Node-Mesh001"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh001_1"
          geometry={nodes["Node-Mesh001_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh001_2"
          geometry={nodes["Node-Mesh001_2"].geometry}
          material={textureMaterial}
        />
      </motion.group>
      <group
        name="keyboard"
        position={[0.215, 0.981, -1.215]}
        rotation={[0, -0.224, 0]}
      >
        <mesh
          name="mesh425587018"
          geometry={nodes.mesh425587018.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh425587018_1"
          geometry={nodes.mesh425587018_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh425587018_2"
          geometry={nodes.mesh425587018_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh425587018_3"
          geometry={nodes.mesh425587018_3.geometry}
          material={textureMaterial}
        />
      </group>
      <motion.group
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
        name="iMac"
        position={[0.454, 0.939, -1.723]}
        rotation={[Math.PI, -1.099, Math.PI]}
      >
        <mesh
          name="iMac_1"
          geometry={nodes.iMac_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="iMac_1_1"
          geometry={nodes.iMac_1_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="iMac_1_2"
          geometry={nodes.iMac_1_2.geometry}
          material={textureMaterial}
        />
      </motion.group>
      <mesh
        name="Comp_Mouse"
        geometry={nodes.Comp_Mouse.geometry}
        material={textureMaterial}
        position={[-0.008, 0, 0.076]}
      />
      <motion.group
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
        name="Chair"
        position={[0.089, 0, -0.664]}
        rotation={[0, -0.35, 0]}
      >
        <mesh
          name="Node-Mesh"
          geometry={nodes["Node-Mesh"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh_1"
          geometry={nodes["Node-Mesh_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh_2"
          geometry={nodes["Node-Mesh_2"].geometry}
          material={materials["Material.001"]}
        />
      </motion.group>
      <mesh
        name="Screen"
        geometry={nodes.Screen.geometry}
        position={[0.45, 0.94, -1.72]}
        rotation={[Math.PI, -1.1, Math.PI]}
      >
        <meshBasicMaterial map={textureVSCode} toneMapped={false} />
      </mesh>
      <group
        name="avacado"
        position={[-0.565, 1.194, -1.547]}
        rotation={[3.049, -1.549, Math.PI]}
      >
        <mesh
          name="mesh553117712"
          geometry={nodes.mesh553117712.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh553117712_1"
          geometry={nodes.mesh553117712_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh553117712_2"
          geometry={nodes.mesh553117712_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh553117712_3"
          geometry={nodes.mesh553117712_3.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh553117712_4"
          geometry={nodes.mesh553117712_4.geometry}
          material={textureMaterial}
        />
      </group>
      <motion.group
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
        name="Owl_01_Cube027"
        position={[0.417, 1.977, -2.117]}
        rotation={[Math.PI, -1.351, Math.PI]}
      >
        <mesh
          name="Owl_01_Cube027_1"
          geometry={nodes.Owl_01_Cube027_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Owl_01_Cube027_1_1"
          geometry={nodes.Owl_01_Cube027_1_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Owl_01_Cube027_1_2"
          geometry={nodes.Owl_01_Cube027_1_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Owl_01_Cube027_1_3"
          geometry={nodes.Owl_01_Cube027_1_3.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Owl_01_Cube027_1_4"
          geometry={nodes.Owl_01_Cube027_1_4.geometry}
          material={textureMaterial}
        />
      </motion.group>

      <motion.group
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
        name="FlowerPot4"
        position={[-2.052, 1.01, -1.476]}
      >
        <mesh
          name="FlowerPot4_1"
          geometry={nodes.FlowerPot4_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="FlowerPot4_2"
          geometry={nodes.FlowerPot4_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="FlowerPot4_3"
          geometry={nodes.FlowerPot4_3.geometry}
          material={textureMaterial}
        />
      </motion.group>
      <motion.group
        scale={[0, 0, 0]}
        animate={{
          scale: section === 0 ? 1 : 0,
        }}
        name="bike"
        position={[0.244, 0, 1.725]}
        rotation={[-0.192, 1.5, 0]}
      >
        <mesh
          name="Circle004-Mesh"
          geometry={nodes["Circle004-Mesh"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Circle004-Mesh_1"
          geometry={nodes["Circle004-Mesh_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Circle004-Mesh_2"
          geometry={nodes["Circle004-Mesh_2"].geometry}
          material={textureMaterial}
        />
      </motion.group>

      <mesh
        name="Plane001"
        geometry={nodes.Plane001.geometry}
        material={textureMaterial}
      />
      <mesh
        name="Plane001_1"
        geometry={nodes.Plane001_1.geometry}
        material={textureGlassMaterial}
      />
      <mesh
        name="Plane001_2"
        geometry={nodes.Plane001_2.geometry}
        material={textureMaterial}
      />
      <mesh
        name="Plane001_3"
        geometry={nodes.Plane001_3.geometry}
        material={textureMaterial}
      />
    </group>
  );
}

useGLTF.preload("models/portfolio_scene_baked_final.gltf");
